name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.2.5'
        cabal-version: '3.6.3.0'
        enable-stack: true

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yml') }}-${{ hashFiles('package.yml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        stack update
        stack build --only-dependencies
    - name: Build
      run: stack build
    - name: Run tests
      run: stack test
